#!/bin/bash
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --gres=gpu:1
#SBATCH --time=08:00:00
#SBATCH --job-name=catch22_attack_gpu
#SBATCH --mem=96GB
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --output=logs/%x-%j.out
#SBATCH --error=logs/%x-%j.err

set -euo pipefail

ROOT="${CATCH22_ROOT:?source env.sh first}"
# shellcheck source=/dev/null
source "$ROOT/common/slurm/hpc_env.sh"

MANIFEST="${MANIFEST:?MANIFEST is required}"
ATTACK_NAME="${ATTACK_NAME:?ATTACK_NAME is required}"
INPUT_FILE="${INPUT_FILE:?INPUT_FILE is required}"
OUTPUT_FILE="${OUTPUT_FILE:?OUTPUT_FILE is required}"
SUMMARY_FILE="${SUMMARY_FILE:?SUMMARY_FILE is required}"
SOURCE_MODEL="${SOURCE_MODEL:-}"
ATTACK_MODEL="${ATTACK_MODEL:-}"
FORWARD_MODEL="${FORWARD_MODEL:-}"
BACKWARD_MODEL="${BACKWARD_MODEL:-}"
TORCH_DTYPE="${TORCH_DTYPE:-float16}"
BATCH_SAVE="${BATCH_SAVE:-5}"
NUM_SAMPLES="${NUM_SAMPLES:-}"
TARGET_EDIT_RATE="${TARGET_EDIT_RATE:-0.15}"
DIPPER_LEXICAL_DIVERSITY="${DIPPER_LEXICAL_DIVERSITY:-40}"
DIPPER_ORDER_DIVERSITY="${DIPPER_ORDER_DIVERSITY:-0}"
DIPPER_SENT_INTERVAL="${DIPPER_SENT_INTERVAL:-3}"
SPAN_MIN_LENGTH="${SPAN_MIN_LENGTH:-5}"
SPAN_MAX_LENGTH="${SPAN_MAX_LENGTH:-10}"

case "$ATTACK_NAME" in
  dipper)
    DEFAULT_ATTACK_BATCH_SIZE="${DEFAULT_ATTACK_BATCH_SIZE:-8}"
    ;;
  opt|wm-removal|summarization)
    DEFAULT_ATTACK_BATCH_SIZE="${DEFAULT_ATTACK_BATCH_SIZE:-16}"
    ;;
  *)
    DEFAULT_ATTACK_BATCH_SIZE="${DEFAULT_ATTACK_BATCH_SIZE:-8}"
    ;;
esac
ATTACK_BATCH_SIZE="${ATTACK_BATCH_SIZE:-$DEFAULT_ATTACK_BATCH_SIZE}"
export CAUSAL_LM_FORCE_CUDA="${CAUSAL_LM_FORCE_CUDA:-1}"
export CAUSAL_LM_GENERATION_BATCH_SIZE="${CAUSAL_LM_GENERATION_BATCH_SIZE:-$ATTACK_BATCH_SIZE}"
export CAUSAL_LM_MIN_GENERATION_BATCH_SIZE="${CAUSAL_LM_MIN_GENERATION_BATCH_SIZE:-1}"
export SUMMARIZATION_GENERATION_BATCH_SIZE="${SUMMARIZATION_GENERATION_BATCH_SIZE:-$ATTACK_BATCH_SIZE}"
export SUMMARIZATION_MIN_GENERATION_BATCH_SIZE="${SUMMARIZATION_MIN_GENERATION_BATCH_SIZE:-1}"
export SEQ2SEQ_FORCE_CUDA="${SEQ2SEQ_FORCE_CUDA:-1}"
export OMP_NUM_THREADS="${OMP_NUM_THREADS:-${SLURM_CPUS_PER_TASK:-4}}"
export MKL_NUM_THREADS="${MKL_NUM_THREADS:-${SLURM_CPUS_PER_TASK:-4}}"
export NUMEXPR_NUM_THREADS="${NUMEXPR_NUM_THREADS:-${SLURM_CPUS_PER_TASK:-4}}"
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"

if [[ "$ATTACK_NAME" == "dipper" ]]; then
  export DIPPER_GENERATION_BATCH_SIZE="${DIPPER_GENERATION_BATCH_SIZE:-8}"
  export DIPPER_MIN_GENERATION_BATCH_SIZE="${DIPPER_MIN_GENERATION_BATCH_SIZE:-1}"
  export DIPPER_PAD_TO_MULTIPLE_OF="${DIPPER_PAD_TO_MULTIPLE_OF:-8}"
  echo "Dipper GPU tuning: SEQ2SEQ_FORCE_CUDA=$SEQ2SEQ_FORCE_CUDA ATTACK_BATCH_SIZE=$ATTACK_BATCH_SIZE DIPPER_GENERATION_BATCH_SIZE=$DIPPER_GENERATION_BATCH_SIZE DIPPER_MIN_GENERATION_BATCH_SIZE=$DIPPER_MIN_GENERATION_BATCH_SIZE DIPPER_PAD_TO_MULTIPLE_OF=$DIPPER_PAD_TO_MULTIPLE_OF PYTORCH_CUDA_ALLOC_CONF=$PYTORCH_CUDA_ALLOC_CONF"
elif [[ "$ATTACK_NAME" == "opt" || "$ATTACK_NAME" == "wm-removal" ]]; then
  echo "Causal LM GPU tuning: CAUSAL_LM_FORCE_CUDA=$CAUSAL_LM_FORCE_CUDA ATTACK_BATCH_SIZE=$ATTACK_BATCH_SIZE CAUSAL_LM_GENERATION_BATCH_SIZE=$CAUSAL_LM_GENERATION_BATCH_SIZE PYTORCH_CUDA_ALLOC_CONF=$PYTORCH_CUDA_ALLOC_CONF"
elif [[ "$ATTACK_NAME" == "summarization" ]]; then
  echo "Seq2seq summarization GPU tuning: SEQ2SEQ_FORCE_CUDA=$SEQ2SEQ_FORCE_CUDA ATTACK_BATCH_SIZE=$ATTACK_BATCH_SIZE SUMMARIZATION_GENERATION_BATCH_SIZE=$SUMMARIZATION_GENERATION_BATCH_SIZE PYTORCH_CUDA_ALLOC_CONF=$PYTORCH_CUDA_ALLOC_CONF"
fi

cmd=(
  python3 "$ROOT/common/run_attack_suite.py"
  --manifest "$MANIFEST"
  --attack-name "$ATTACK_NAME"
  --input-file "$INPUT_FILE"
  --output-file "$OUTPUT_FILE"
  --summary-file "$SUMMARY_FILE"
  --torch-dtype "$TORCH_DTYPE"
  --batch-save "$BATCH_SAVE"
  --attack-batch-size "$ATTACK_BATCH_SIZE"
  --target-edit-rate "$TARGET_EDIT_RATE"
  --dipper-lexical-diversity "$DIPPER_LEXICAL_DIVERSITY"
  --dipper-order-diversity "$DIPPER_ORDER_DIVERSITY"
  --dipper-sent-interval "$DIPPER_SENT_INTERVAL"
  --span-min-length "$SPAN_MIN_LENGTH"
  --span-max-length "$SPAN_MAX_LENGTH"
)
[[ -n "$NUM_SAMPLES" ]] && cmd+=(--num-samples "$NUM_SAMPLES")
[[ -n "$SOURCE_MODEL" ]] && cmd+=(--source-model "$SOURCE_MODEL")
[[ -n "$ATTACK_MODEL" ]] && cmd+=(--attack-model "$ATTACK_MODEL")
[[ -n "$FORWARD_MODEL" ]] && cmd+=(--forward-model "$FORWARD_MODEL")
[[ -n "$BACKWARD_MODEL" ]] && cmd+=(--backward-model "$BACKWARD_MODEL")
"${cmd[@]}"
